# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=50)),
            ],
        ),
    ]
