# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPage', '0003_auto_20161006_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_name',
            old_name='stud_name',
            new_name='student_name',
        ),
    ]
