# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPage', '0004_auto_20161006_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_name',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
