# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPage', '0005_student_name_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialisation',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='InfoPage.student_name'),
        ),
    ]
