# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPage', '0007_student_name_spec1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_name',
            name='spec1',
            field=models.TextField(default='Enter specialization information here.', max_length=500),
        ),
    ]
