# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPage', '0008_auto_20161007_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialisation',
            name='student',
        ),
        migrations.DeleteModel(
            name='Specialisation',
        ),
    ]
